PROGRAM Response(INPUT, OUTPUT);

USES
  DOS;

BEGIN
  WRITELN('Content-Type:text/plain');
  WRITELN;
  WRITELN(GETENV('REQUEST_METHOD'));
  WRITELN(GETENV('QUERY_STRING'));// строка со всеми переменными
  WRITELN(GETENV('CONTENT_LENGTH'));
  WRITELN(GETENV('HTTP_USER_AGENT'));
  WRITELN(GETENV('HTTP_HOST'));
END.
